%{
type ast = 
    | Add of ast * ast 
    | Mul of ast * ast 
    | Num of int 
%}

description = "Grammar for simple arithmetic expressions"
whitespace = [ "\n", "\t", " ", "\r" ]
start = expr 

%% 

number: n = r"[1-9][0-9]*" { int_of_string n }

%% 

expr: 
    t = term "+" e = expr { Add(t, e) }
    / t = term { t }

term: 
    a = atom "*" t = term { Mul(a, t) }
    / a = atom { a }

atom: 
    n = number { Num( n ) }
    / "(" e = expr ")" { e }
